name: country_code_picker
description: A flutter package for showing a country code selector.
version: 1.0.4
author: Salvatore-Giordano <svtgiordano@gmail.com>
homepage: https://github.com/Salvatore-Giordano/CountryCodePicker

environment:
  sdk: ">=1.19.0  <3.0.0"

dependencies:
  flutter:
    sdk: flutter
